name: "Rollup / JS build"

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Rollup
      run: |
        yarn
        rollup -c
        rollup -c rollup.esm.js
