name: "Rollup / JS build"

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Rollup
      run: |
        yarn
        yarn run rollup -c
        yarn run rollup -c rollup.esm.js
